doctrine:
    dbal:
        connections:
            default:
                url: "%env(resolve:DATABASE_URL)%"
            compras:
                url: "%env(resolve:DATABASE_COMPRAS_URL)%"

            profiling_collect_backtrace: "%kernel.debug%"
        default_connection: default

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        # report_fields_where_declared: true
        # validate_xml_mapping: true
        # naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        # auto_mapping: true

        entity_managers:
            default:
                connection: default
                mappings:
                    AppCore:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Core/Entity"
                        prefix: 'App\Core\Entity'
                        alias: AppCore
                    AppSupply:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Supply/Entity"
                        prefix: 'App\Supply\Entity'
                        alias: AppSupply

            compras:
                connection: compras
                mappings:
                    AppCore:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Core/Entity"
                        prefix: 'App\Core\Entity'
                        alias: AppCore
                    AppSupply:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Supply/Entity"
                        prefix: 'App\Supply\Entity'
                        alias: AppSupply

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
