doctrine:
    dbal:
        connections:
            default:
                url: "%env(resolve:DATABASE_URL)%"
                logging: "%kernel.debug%"
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_bin
            compras:
                url: "%env(resolve:DATABASE_COMPRAS_URL)%"
                logging: "%kernel.debug%"
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_bin
        #     profiling_collect_backtrace: "%kernel.debug%"
        default_connection: default

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
        types:
            operacao: 'App\Core\Doctrine\DBAL\Types\OperacaoType'
            httpMethod: 'App\Core\Doctrine\DBAL\Types\HttpMethodType'
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        default_entity_manager: default
        #auto_generate_proxy_classes: true
        #enable_lazy_ghost_objects: true
        # report_fields_where_declared: true
        # validate_xml_mapping: true
        # \\naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        # auto_mapping: true

        entity_managers:
            default:
                dql:
                    string_functions:
                        AES_DECRYPT_FROM_BASE64: App\Core\Doctrine\DQL\AesDecryptFromBase64
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Core/Entity"
                        prefix: 'App\Core\Entity'
                        alias: App
                    AppLog:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Core/Entity/Log"
                        prefix: 'App\Core\Entity\Log'
                        alias: AppLog
                    Supply:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Supply/Entity"
                        prefix: 'App\Supply\Entity'
                        alias: Supply

            compras:
                dql:
                    string_functions:
                        AES_DECRYPT_FROM_BASE64: App\Core\Doctrine\DQL\AesDecryptFromBase64
                connection: compras
                mappings:
                    App:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Core/Entity"
                        prefix: 'App\Core\Entity'
                        alias: App
                    Supply:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Supply/Entity"
                        prefix: 'App\Supply\Entity'
                        alias: Supply
                    SupplyLog:
                        is_bundle: false
                        dir: "%kernel.project_dir%/src/Supply/Entity/Log"
                        prefix: 'App\Supply\Entity\Log'
                        alias: SupplyLog

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
