version: '3'

services:
    ilogix_alpha-app:
        build:
            context: .
            args:
                uid: '${UID}'
        container_name: ilogix_alpha-app
        ports:
        - '8000:8000'
        volumes:
        - '.:/app'
        #stdin_open: true
        #tty: true
        networks:
            backend:
                aliases:
                    - app
        restart: always
    database:
        ports:
            - '3306:3306'
        container_name: ilogix_alpha-mariadb-db
        image: mariadb:11.1.2
        volumes:
            - './run/var:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
            MYSQL_USER: ${MYSQL_USER:-app}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
        networks:
            backend:
                aliases:
                    - mariadb-db
networks:
  backend:
    name: backend
