app_routes:
    resource:
        path: ../src/Core/Controller/
        namespace: App\Core\Controller
    type: attribute
    prefix: /api

supply_routes:
    resource:
        path: ../src/Supply/Controller/
        namespace: App\Supply\Controller
    type: attribute
    prefix: /api/supply

api_login_check:
    path: /api/login_check
